#!/bin/bash
echo ""
echo ""
echo "$(tput setaf 6)___________________________________________________________________________________________________________________"
echo "$(tput setaf 6)___________________________________________________________________________________________________________________"
echo ""
echo ""
echo "  $(tput setaf 6)     QQQQQQQQQ                                                             tttt                              "
echo "  $(tput setaf 6)   QQ:::::::::QQ                                                        ttt:::t                              "
echo "  $(tput setaf 6) QQ:::::::::::::QQ                                                      t:::::t                              "
echo "  $(tput setaf 6)Q:::::::QQQ:::::::Q                                                     t:::::t                              "
echo "  $(tput setaf 6)Q::::::O   Q::::::Q    uuuuuu    uuuuuu         ooooooooooo       ttttttt:::::ttttttt            eeeeeeeeeeee    "
echo "  $(tput setaf 6)Q:::::O     Q:::::Q    u::::u    u::::u       oo:::::::::::oo     t:::::::::::::::::t          ee::::::::::::ee  "
echo "  $(tput setaf 6)Q:::::O     Q:::::Q    u::::u    u::::u      o:::::::::::::::o    t:::::::::::::::::t         e::::::eeeee:::::ee"
echo "  $(tput setaf 6)Q:::::O     Q:::::Q    u::::u    u::::u      o:::::ooooo:::::o    tttttt:::::::tttttt        e::::::e     e:::::e"
echo "  $(tput setaf 6)Q:::::O     Q:::::Q    u::::u    u::::u      o::::o     o::::o          t:::::t              e:::::::eeeee::::::e"
echo "  $(tput setaf 6)Q:::::O     Q:::::Q    u::::u    u::::u      o::::o     o::::o          t:::::t              e:::::::::::::::::e "
echo "  $(tput setaf 6)Q:::::O  QQQQ:::::Q    u::::u    u::::u      o::::o     o::::o          t:::::t              e::::::eeeeeeeeeee  "
echo "  $(tput setaf 6)Q::::::O Q::::::::Q    u:::::uuuu:::::u      o::::o     o::::o          t:::::t    tttttt    e:::::::e           "
echo "  $(tput setaf 6)Q:::::::QQ::::::::Q    u:::::::::::::::uu    o:::::ooooo:::::o          t::::::tttt:::::t    e::::::::e          "
echo "  $(tput setaf 6) QQ::::::::::::::Q      u:::::::::::::::u    o:::::::::::::::o          tt::::::::::::::t     e::::::::eeeeeeee  "
echo "  $(tput setaf 6)   QQ:::::::::::Q        uu::::::::uu:::u     oo:::::::::::oo             tt:::::::::::tt      ee:::::::::::::e  "
echo "  $(tput setaf 6)     QQQQQQQQ::::QQ        uuuuuuuu  uuuu       ooooooooooo                 ttttttttttt          eeeeeeeeeeeeee  "
echo "  $(tput setaf 6)             Q:::::Q                                                                             "
echo "  $(tput setaf 6)              QQQQQQ                                                                             "
echo ""
echo ""
echo "$(tput setaf 6)___________________________________________________________________________________________________________________"
echo "$(tput setaf 6)___________________________________________________________________________________________________________________"
echo ""
echo ""
echo "$(tput setaf 7)Welcome to $(tput setaf 6)Quote Linux Launcher$(tput setaf 7)."
echo ""
choice=4
  echo "$(tput setaf 3)[1] $(tput setaf 7)Launch"
  echo "$(tput setaf 3)[2] $(tput setaf 7)Download"
  echo "$(tput setaf 3)[3] $(tput setaf 7)Update Core"
  echo "$(tput setaf 3)[3] $(tput setaf 7)Update Modules"
  echo "$(tput setaf 3)[3] $(tput setaf 7)Exit"
  echo ""
  echo "Choose $(tput setaf 3)[1] $(tput setaf 7)to Launch $(tput setaf 6)Quote$(tput setaf 7)"
  echo "Choose $(tput setaf 3)[2] $(tput setaf 7)to Download $(tput setaf 6)Quote$(tput setaf 7)"
  echo "Choose $(tput setaf 3)[3] $(tput setaf 7)to $(tput setaf 6)Update $(tput setaf 7)the $(tput setaf 6)Core$(tput setaf 7)"
  echo "Choose $(tput setaf 3)[4] $(tput setaf 7)to $(tput setaf 6)Update $(tput setaf 7)the $(tput setaf 6)Modules$(tput setaf 7)"
  echo "Choose $(tput setaf 3)[3] $(tput setaf 7)to $(tput setaf 1)Exit$(tput setaf 7)"
  echo ""
