#!/bin/bash
echo ""
echo ""
echo "  $(tput setaf 6)                                                     "
echo "  $(tput setaf 6)   _|_|                            _|                "
echo "  $(tput setaf 6) _|    _|    _|    _|    _|_|    _|_|_|_|    _|_|    "
echo "  $(tput setaf 6) _|  _|_|    _|    _|  _|    _|    _|      _|_|_|_|  "
echo "  $(tput setaf 6) _|    _|    _|    _|  _|    _|    _|      _|        "
echo "  $(tput setaf 6)   _|_|  _|    _|_|_|    _|_|        _|_|    _|_|_|  "
echo "" 
echo "$(tput setaf 7)Welcome to $(tput setaf 6)Quote Linux Launcher$(tput setaf 7)."
echo ""
choice=4
  echo "[1] Download"
  echo "[2] Launch"
  echo "[3] Exit"
  echo -n "Choose $(tput setaf 3)[1] $(tput setaf 7)to Download $(tput setaf 6)Quote, $(tput setaf 7)choose $(tput setaf 3)[2] $(tput setaf 7)to Launch $(tput setaf 6)Quote $(tput setaf 7)or $(tput setaf 3)[3] $(tput setaf 7)to $(tput setaf 1)Exit$(tput setaf 7)"
  echo ""
