#!/bin/bash
echo ""
echo ""
echo "$(tput setaf 6)___________________________________________________________________________________________________"
echo "$(tput setaf 6)___________________________________________________________________________________________________"
echo ""
echo ""
echo "  $(tput setaf 6)     QQQQQQQQQ                                                 tttt                              "
echo "  $(tput setaf 6)   QQ:::::::::QQ                                            ttt:::t                              "
echo "  $(tput setaf 6) QQ:::::::::::::QQ                                          t:::::t                              "
echo "  $(tput setaf 6)Q:::::::QQQ:::::::Q                                         t:::::t                              "
echo "  $(tput setaf 6)Q::::::O   Q::::::Quuuuuu    uuuuuu     ooooooooooo   ttttttt:::::ttttttt        eeeeeeeeeeee    "
echo "  $(tput setaf 6)Q:::::O     Q:::::Qu::::u    u::::u   oo:::::::::::oo t:::::::::::::::::t      ee::::::::::::ee  "
echo "  $(tput setaf 6)Q:::::O     Q:::::Qu::::u    u::::u  o:::::::::::::::ot:::::::::::::::::t     e::::::eeeee:::::ee"
echo "  $(tput setaf 6)Q:::::O     Q:::::Qu::::u    u::::u  o:::::ooooo:::::otttttt:::::::tttttt    e::::::e     e:::::e"
echo "  $(tput setaf 6)Q:::::O     Q:::::Qu::::u    u::::u  o::::o     o::::o      t:::::t          e:::::::eeeee::::::e"
echo "  $(tput setaf 6)Q:::::O     Q:::::Qu::::u    u::::u  o::::o     o::::o      t:::::t          e:::::::::::::::::e "
echo "  $(tput setaf 6)Q:::::O  QQQQ:::::Qu::::u    u::::u  o::::o     o::::o      t:::::t          e::::::eeeeeeeeeee  "
echo "  $(tput setaf 6)Q::::::O Q::::::::Qu:::::uuuu:::::u  o::::o     o::::o      t:::::t    tttttte:::::::e           "
echo "  $(tput setaf 6)Q:::::::QQ::::::::Qu:::::::::::::::uuo:::::ooooo:::::o      t::::::tttt:::::te::::::::e          "
echo "  $(tput setaf 6) QQ::::::::::::::Q  u:::::::::::::::uo:::::::::::::::o      tt::::::::::::::t e::::::::eeeeeeee  "
echo "  $(tput setaf 6)   QQ:::::::::::Q    uu::::::::uu:::u oo:::::::::::oo         tt:::::::::::tt  ee:::::::::::::e  "
echo "  $(tput setaf 6)     QQQQQQQQ::::QQ    uuuuuuuu  uuuu   ooooooooooo             ttttttttttt      eeeeeeeeeeeeee  "
echo "  $(tput setaf 6)             Q:::::Q                                                                             "
echo "  $(tput setaf 6)              QQQQQQ                                                                             "
echo ""
echo ""
echo "$(tput setaf 6)___________________________________________________________________________________________________"
echo "$(tput setaf 6)___________________________________________________________________________________________________"
echo ""
echo ""
echo "$(tput setaf 7)Welcome to $(tput setaf 6)Quote Linux Launcher$(tput setaf 7)."
echo ""
choice=4
  echo "[1] Download"
  echo "[2] Launch"
  echo "[3] Exit"
  echo ""
  echo -n "Choose $(tput setaf 3)[1] $(tput setaf 7)to Download $(tput setaf 6)Quote, $(tput setaf 7)choose $(tput setaf 3)[2] $(tput setaf 7)to Launch $(tput setaf 6)Quote $(tput setaf 7)or $(tput setaf 3)[3] $(tput setaf 7)to $(tput setaf 1)Exit$(tput setaf 7)"
  echo ""
